// Mock data for F1 (UI with mock data). The Backend replaces this with real
// queries in F2 — keep everything conforming to src/lib/types.ts.

import type {
  Application,
  Binding,
  Deployment,
  Domain,
  Project,
  Server,
  ServiceInstance,
  ServiceTemplate,
} from "@/lib/types";

// Fixed "now" so relative timestamps stay deterministic across renders.
export const MOCK_NOW = "2026-07-19T14:30:00.000Z";
export const MOCK_TODAY = "2026-07-19";

export const mockServers: Server[] = [
  {
    id: "srv_01",
    name: "hetzner-fsn1",
    host: "138.201.93.47",
    status: "online",
    cpuCores: 4,
    memoryMb: 8192,
    diskGb: 160,
    cpuUsagePct: 23,
    memoryUsagePct: 61,
    diskUsagePct: 42,
    dockerVersion: "27.1.1",
    createdAt: "2026-05-02T09:14:00.000Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj_01",
    name: "acme-storefront",
    slug: "acme-storefront",
    description: "E-commerce storefront and checkout for Acme Inc.",
    serverId: "srv_01",
    createdAt: "2026-05-03T10:22:00.000Z",
  },
  {
    id: "proj_02",
    name: "taskloop",
    slug: "taskloop",
    description: "Internal project management and analytics tools.",
    serverId: "srv_01",
    createdAt: "2026-05-18T15:41:00.000Z",
  },
  {
    id: "proj_03",
    name: "acme-marketing",
    slug: "acme-marketing",
    description: "Marketing site and campaign landing pages.",
    serverId: "srv_01",
    createdAt: "2026-06-11T08:05:00.000Z",
  },
];

export const mockApplications: Application[] = [
  {
    id: "app_01",
    projectId: "proj_01",
    environment: "production",
    name: "storefront-web",
    framework: "nextjs",
    repoUrl: "https://github.com/acme/storefront-web",
    branch: "main",
    installCommand: "pnpm install",
    buildCommand: "pnpm build",
    startCommand: "pnpm start",
    outputDirectory: null,
    port: 3000,
    status: "running",
    createdAt: "2026-05-03T11:02:00.000Z",
  },
  {
    id: "app_02",
    projectId: "proj_01",
    environment: "production",
    name: "storefront-api",
    framework: "adonisjs",
    repoUrl: "https://github.com/acme/storefront-api",
    branch: "main",
    installCommand: "pnpm install",
    buildCommand: "node ace build",
    startCommand: "node build/bin/server.js",
    outputDirectory: "build",
    port: 3333,
    status: "running",
    createdAt: "2026-05-04T09:30:00.000Z",
  },
  {
    id: "app_03",
    projectId: "proj_02",
    environment: "production",
    name: "taskloop-app",
    framework: "sveltekit",
    repoUrl: "https://github.com/acme/taskloop",
    branch: "main",
    installCommand: "pnpm install",
    buildCommand: "pnpm build",
    startCommand: "node build/index.js",
    outputDirectory: "build",
    port: 3000,
    status: "building",
    createdAt: "2026-05-18T16:10:00.000Z",
  },
  {
    id: "app_04",
    projectId: "proj_02",
    environment: "production",
    name: "taskloop-analytics",
    framework: "django",
    repoUrl: "https://github.com/acme/taskloop-analytics",
    branch: "main",
    installCommand: "pip install -r requirements.txt",
    buildCommand: null,
    startCommand: "gunicorn analytics.wsgi",
    outputDirectory: null,
    port: 8000,
    status: "stopped",
    createdAt: "2026-06-02T13:45:00.000Z",
  },
  {
    id: "app_05",
    projectId: "proj_03",
    environment: "production",
    name: "acme-website",
    framework: "static",
    repoUrl: "https://github.com/acme/acme-website",
    branch: "main",
    installCommand: "pnpm install",
    buildCommand: "pnpm build",
    startCommand: null,
    outputDirectory: "dist",
    port: 80,
    status: "running",
    createdAt: "2026-06-11T08:20:00.000Z",
  },
];

export const mockDeployments: Deployment[] = [
  {
    id: "dep_01",
    applicationId: "app_01",
    status: "running",
    commitSha: "9f3c2ab",
    commitMessage: "fix: correct cart total rounding on checkout",
    branch: "main",
    triggeredBy: "rodrigo",
    startedAt: "2026-07-19T13:02:00.000Z",
    finishedAt: "2026-07-19T13:04:47.000Z",
    durationSec: 167,
  },
  {
    id: "dep_02",
    applicationId: "app_03",
    status: "building",
    commitSha: "5b81d90",
    commitMessage: "feat: kanban board drag-and-drop",
    branch: "main",
    triggeredBy: "webhook",
    startedAt: "2026-07-19T14:21:00.000Z",
    finishedAt: null,
    durationSec: null,
  },
  {
    id: "dep_03",
    applicationId: "app_02",
    status: "running",
    commitSha: "c47e112",
    commitMessage: "feat: add PIX payment provider",
    branch: "main",
    triggeredBy: "webhook",
    startedAt: "2026-07-19T10:15:00.000Z",
    finishedAt: "2026-07-19T10:18:34.000Z",
    durationSec: 214,
  },
  {
    id: "dep_04",
    applicationId: "app_05",
    status: "failed",
    commitSha: "d0a9b31",
    commitMessage: "chore: migrate hero images to AVIF",
    branch: "main",
    triggeredBy: "rodrigo",
    startedAt: "2026-07-19T09:47:00.000Z",
    finishedAt: "2026-07-19T09:47:58.000Z",
    durationSec: 58,
  },
  {
    id: "dep_05",
    applicationId: "app_01",
    status: "deploying",
    commitSha: "71fe0c4",
    commitMessage: "feat: product reviews section",
    branch: "main",
    triggeredBy: "rodrigo",
    startedAt: "2026-07-19T14:28:00.000Z",
    finishedAt: null,
    durationSec: null,
  },
  {
    id: "dep_06",
    applicationId: "app_04",
    status: "cancelled",
    commitSha: "b2261f8",
    commitMessage: "refactor: extract report generator",
    branch: "main",
    triggeredBy: "rodrigo",
    startedAt: "2026-07-18T17:32:00.000Z",
    finishedAt: "2026-07-18T17:33:12.000Z",
    durationSec: null,
  },
  {
    id: "dep_07",
    applicationId: "app_02",
    status: "failed",
    commitSha: "8d914c7",
    commitMessage: "fix: webhook retry backoff",
    branch: "fix/webhooks",
    triggeredBy: "webhook",
    startedAt: "2026-07-18T11:08:00.000Z",
    finishedAt: "2026-07-18T11:09:36.000Z",
    durationSec: 96,
  },
  {
    id: "dep_08",
    applicationId: "app_01",
    status: "running",
    commitSha: "3e5d6f0",
    commitMessage: "feat: checkout A/B experiment",
    branch: "main",
    triggeredBy: "webhook",
    startedAt: "2026-07-17T16:44:00.000Z",
    finishedAt: "2026-07-17T16:47:09.000Z",
    durationSec: 189,
  },
];

export const mockDomains: Domain[] = [
  {
    id: "dom_01",
    applicationId: "app_01",
    hostname: "shop.acme.com",
    isPrimary: true,
    sslStatus: "active",
    createdAt: "2026-05-03T11:30:00.000Z",
  },
  {
    id: "dom_02",
    applicationId: "app_01",
    hostname: "storefront-web.olym.app",
    isPrimary: false,
    sslStatus: "active",
    createdAt: "2026-05-03T11:05:00.000Z",
  },
  {
    id: "dom_03",
    applicationId: "app_02",
    hostname: "api.acme.com",
    isPrimary: true,
    sslStatus: "active",
    createdAt: "2026-05-04T10:00:00.000Z",
  },
  {
    id: "dom_04",
    applicationId: "app_03",
    hostname: "taskloop.olym.app",
    isPrimary: true,
    sslStatus: "pending",
    createdAt: "2026-05-18T16:30:00.000Z",
  },
  {
    id: "dom_05",
    applicationId: "app_05",
    hostname: "acme.com",
    isPrimary: true,
    sslStatus: "active",
    createdAt: "2026-06-11T08:40:00.000Z",
  },
  {
    id: "dom_06",
    applicationId: "app_05",
    hostname: "www.acme.com",
    isPrimary: false,
    sslStatus: "active",
    createdAt: "2026-06-11T08:41:00.000Z",
  },
];

export const mockServiceTemplates: ServiceTemplate[] = [
  {
    id: "tpl_postgres",
    name: "PostgreSQL",
    description: "Relational database with battle-tested reliability.",
    category: "database",
    defaultVersion: "17.2",
  },
  {
    id: "tpl_redis",
    name: "Redis",
    description: "In-memory key-value store for caching and queues.",
    category: "cache",
    defaultVersion: "7.4",
  },
  {
    id: "tpl_minio",
    name: "MinIO",
    description: "S3-compatible object storage.",
    category: "storage",
    defaultVersion: "2026-01-15",
  },
];

export const mockServiceInstances: ServiceInstance[] = [
  {
    id: "svc_01",
    projectId: "proj_01",
    environment: "production",
    templateId: "tpl_postgres",
    name: "storefront-db",
    version: "17.2",
    status: "running",
    createdAt: "2026-05-03T10:40:00.000Z",
  },
  {
    id: "svc_02",
    projectId: "proj_01",
    environment: "production",
    templateId: "tpl_redis",
    name: "storefront-cache",
    version: "7.4",
    status: "running",
    createdAt: "2026-05-03T10:42:00.000Z",
  },
  {
    id: "svc_03",
    projectId: "proj_02",
    environment: "production",
    templateId: "tpl_postgres",
    name: "taskloop-db",
    version: "16.6",
    status: "running",
    createdAt: "2026-05-18T16:00:00.000Z",
  },
  {
    id: "svc_04",
    projectId: "proj_02",
    environment: "production",
    templateId: "tpl_minio",
    name: "taskloop-files",
    version: "2026-01-15",
    status: "running",
    createdAt: "2026-06-02T14:00:00.000Z",
  },
];

export const mockBindings: Binding[] = [
  { id: "bind_01", applicationId: "app_01", serviceInstanceId: "svc_01", injectedVarKey: "DATABASE_URL", createdAt: "2026-05-03T11:12:00.000Z" },
  { id: "bind_02", applicationId: "app_01", serviceInstanceId: "svc_02", injectedVarKey: "REDIS_URL", createdAt: "2026-05-03T11:14:00.000Z" },
  { id: "bind_03", applicationId: "app_02", serviceInstanceId: "svc_01", injectedVarKey: "DATABASE_URL", createdAt: "2026-05-04T09:45:00.000Z" },
  { id: "bind_04", applicationId: "app_03", serviceInstanceId: "svc_03", injectedVarKey: "DATABASE_URL", createdAt: "2026-05-18T16:12:00.000Z" },
];
