#!/usr/bin/env bash
# Olym one-liner installer — draft (F1).
#   curl -fsSL https://get.olym.sh | bash
# Installs Docker if missing, writes /opt/olym/{docker-compose.yml,.env}
# and starts the stack (olym + postgres + redis + traefik).
# No domain is required at install time — the dashboard is reachable
# over plain HTTP on this server's public IP immediately. Configure a
# real domain (and HTTPS) later from Settings inside the dashboard.

set -euo pipefail

OLYM_DIR="${OLYM_DIR:-/opt/olym}"
COMPOSE_URL="${COMPOSE_URL:-https://raw.githubusercontent.com/theinovit/olym/main/docker/docker-compose.prod.yml}"

log() { printf '\033[1;36m[olym]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[olym]\033[0m %s\n' "$*" >&2; exit 1; }

port_is_listening() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltnH | awk '{print $4}' | grep -Eq "(^|:|\\])${port}$"
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn | awk 'NR > 2 {print $4}' | grep -Eq "(^|:|\\])${port}$"
  else
    fail "Cannot check ports: install iproute2 (ss) or net-tools (netstat), then re-run."
  fi
}

check_required_ports() {
  local existing_traefik
  existing_traefik="$(docker compose --project-directory "$OLYM_DIR" ps -q traefik 2>/dev/null || true)"
  [ -n "$existing_traefik" ] && return
  local occupied=()
  port_is_listening 80 && occupied+=(80)
  port_is_listening 443 && occupied+=(443)
  [ "${#occupied[@]}" -eq 0 ] || fail \
    "Port(s) ${occupied[*]} already in use. Stop the conflicting web server/process: Traefik requires exclusive access to ports 80 and 443."
}

ufw_allows_port() {
  local port="$1"
  ufw status | awk -v wanted="$port" '
    $2 == "ALLOW" {
      rule = $1
      sub(/\/tcp$/, "", rule)
      count = split(rule, ports, ",")
      for (index = 1; index <= count; index++) {
        if (ports[index] == wanted) found = 1
      }
    }
    END { exit(found ? 0 : 1) }
  '
}

check_ufw() {
  command -v ufw >/dev/null 2>&1 || return
  ufw status | grep -q '^Status: active' || return
  if ufw status verbose | grep -Eq '^Default: allow \(incoming\)' ||
    { ufw_allows_port 80 && ufw_allows_port 443; }; then
    return
  fi

  log "UFW is active and does not allow both TCP ports 80 and 443."
  if [ -t 0 ]; then
    local answer
    read -rp "Allow ports 80 and 443 for Traefik now? [y/N] " answer
    case "$answer" in
      y|Y|yes|YES) ufw allow 80,443/tcp ;;
      *) fail "Firewall unchanged. Run 'ufw allow 80,443/tcp' and re-run the installer." ;;
    esac
  else
    fail "UFW blocks web traffic. Run 'ufw allow 80,443/tcp' explicitly and re-run the installer."
  fi
}

detect_public_ip() {
  local ip=""
  ip="$(curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null || true)"
  if [ -z "$ip" ]; then
    ip="$(curl -fsSL --max-time 5 https://icanhazip.com 2>/dev/null | tr -d '[:space:]' || true)"
  fi
  if [ -z "$ip" ]; then
    # Last-resort fallback: primary interface address (may be a private/NAT
    # IP behind some providers — DNS verification in Settings will catch a
    # mismatch and tell the user explicitly).
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  [ -n "$ip" ] || fail "Could not detect this server's public IP. Set OLYM_PUBLIC_IP=<ip> and re-run."
  printf '%s' "$ip"
}

[ "$(id -u)" -eq 0 ] || fail "Run as root (or via sudo)."
[ "$(uname -s)" = "Linux" ] || fail "The installer targets Linux servers."

# 1. Docker
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 plugin is required."

# 2. Layout + compose file
mkdir -p "$OLYM_DIR"
log "Downloading compose file to $OLYM_DIR/docker-compose.yml"
curl -fsSL "$COMPOSE_URL" -o "$OLYM_DIR/docker-compose.yml"

# 3. .env (generated once; kept on re-run)
if [ ! -f "$OLYM_DIR/.env" ]; then
  log "Generating $OLYM_DIR/.env"
  PUBLIC_IP="${OLYM_PUBLIC_IP:-$(detect_public_ip)}"
  log "Detected public IP: $PUBLIC_IP"
  cat > "$OLYM_DIR/.env" <<EOF
# Olym configuration — generated by install.sh
OLYM_PUBLIC_IP=$PUBLIC_IP
POSTGRES_PASSWORD=$(openssl rand -hex 24)
OLYM_SECRET=$(openssl rand -hex 32)
EOF
  chmod 600 "$OLYM_DIR/.env"
else
  log "Keeping existing $OLYM_DIR/.env"
fi

# 4. Up
check_required_ports
check_ufw
log "Starting Olym stack..."
docker compose --project-directory "$OLYM_DIR" up -d

PUBLIC_IP="$(grep '^OLYM_PUBLIC_IP=' "$OLYM_DIR/.env" | cut -d= -f2-)"
log "Done. Dashboard: http://$PUBLIC_IP"
log "No domain configured yet — the dashboard is reachable over plain HTTP on this IP."
log "Once you've pointed a DNS A record at this server, open Settings inside the dashboard to enable HTTPS on your own domain (applied live, no restart needed)."
