#!/usr/bin/env bash
# Olym one-liner installer — draft (F1).
#   curl -fsSL https://get.olym.sh | bash
# Installs Docker if missing, writes /opt/olym/{docker-compose.yml,.env}
# and starts the stack (olym + postgres + redis + traefik).

set -euo pipefail

OLYM_DIR="${OLYM_DIR:-/opt/olym}"
COMPOSE_URL="${COMPOSE_URL:-https://raw.githubusercontent.com/theinovit/olym/main/docker/docker-compose.prod.yml}"

log() { printf '\033[1;36m[olym]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[olym]\033[0m %s\n' "$*" >&2; exit 1; }

valid_domain() {
  local host="$1"
  [[ "$host" == *.* ]] &&
    [[ ! "$host" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] &&
    [[ ! "$host" =~ [/:[:space:]] ]]
}

port_is_listening() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltnH | awk '{print $4}' | grep -Eq "(^|:|\\])${port}$"
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn | awk 'NR > 2 {print $4}' | grep -Eq "(^|:|\\])${port}$"
  else
    fail "Cannot check ports: install iproute2 (ss) or net-tools (netstat), then re-run."
  fi
}

check_required_ports() {
  local existing_traefik
  existing_traefik="$(docker compose --project-directory "$OLYM_DIR" ps -q traefik 2>/dev/null || true)"
  [ -n "$existing_traefik" ] && return
  local occupied=()
  port_is_listening 80 && occupied+=(80)
  port_is_listening 443 && occupied+=(443)
  [ "${#occupied[@]}" -eq 0 ] || fail \
    "Port(s) ${occupied[*]} already in use. Stop the conflicting web server/process: Traefik requires exclusive access to ports 80 and 443."
}

ufw_allows_port() {
  local port="$1"
  ufw status | awk -v wanted="$port" '
    $2 == "ALLOW" {
      rule = $1
      sub(/\/tcp$/, "", rule)
      count = split(rule, ports, ",")
      for (index = 1; index <= count; index++) {
        if (ports[index] == wanted) found = 1
      }
    }
    END { exit(found ? 0 : 1) }
  '
}

check_ufw() {
  command -v ufw >/dev/null 2>&1 || return
  ufw status | grep -q '^Status: active' || return
  if ufw status verbose | grep -Eq '^Default: allow \(incoming\)' ||
    { ufw_allows_port 80 && ufw_allows_port 443; }; then
    return
  fi

  log "UFW is active and does not allow both TCP ports 80 and 443."
  if [ -t 0 ]; then
    local answer
    read -rp "Allow ports 80 and 443 for Traefik now? [y/N] " answer
    case "$answer" in
      y|Y|yes|YES) ufw allow 80,443/tcp ;;
      *) fail "Firewall unchanged. Run 'ufw allow 80,443/tcp' and re-run the installer." ;;
    esac
  else
    fail "UFW blocks web traffic. Run 'ufw allow 80,443/tcp' explicitly and re-run the installer."
  fi
}

[ "$(id -u)" -eq 0 ] || fail "Run as root (or via sudo)."
[ "$(uname -s)" = "Linux" ] || fail "The installer targets Linux servers."

# 1. Docker
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 plugin is required."

# 2. Layout + compose file
mkdir -p "$OLYM_DIR"
log "Downloading compose file to $OLYM_DIR/docker-compose.yml"
curl -fsSL "$COMPOSE_URL" -o "$OLYM_DIR/docker-compose.yml"

# 3. .env (generated once; kept on re-run)
if [ ! -f "$OLYM_DIR/.env" ]; then
  log "Generating $OLYM_DIR/.env"
  log "OLYM_HOST must be a real domain (for example painel.suaempresa.com), not a raw IP."
  log "Create its DNS A record pointing to this VPS before continuing; Let's Encrypt HTTP-01 depends on it."
  if [ -z "${OLYM_HOST:-}" ] && [ -t 0 ]; then
    read -rp "Public domain for this Olym instance: " OLYM_HOST
  fi
  [ -n "${OLYM_HOST:-}" ] || fail "Set OLYM_HOST=painel.suaempresa.com after configuring its DNS A record, then re-run."
  valid_domain "$OLYM_HOST" || fail "OLYM_HOST must be a hostname such as painel.suaempresa.com (no scheme, path, port, or raw IP)."
  # ACME_EMAIL is required for Let's Encrypt; prompt when not provided via env.
  if [ -z "${ACME_EMAIL:-}" ]; then
    if [ -t 0 ]; then
      read -rp "Email for Let's Encrypt (SSL) notifications: " ACME_EMAIL
    fi
    [ -n "${ACME_EMAIL:-}" ] || fail "Set ACME_EMAIL=you@example.com and re-run (required for SSL certificates)."
  fi
  cat > "$OLYM_DIR/.env" <<EOF
# Olym configuration — generated by install.sh
OLYM_HOST=$OLYM_HOST
ACME_EMAIL=$ACME_EMAIL
POSTGRES_PASSWORD=$(openssl rand -hex 24)
OLYM_SECRET=$(openssl rand -hex 32)
EOF
  chmod 600 "$OLYM_DIR/.env"
else
  log "Keeping existing $OLYM_DIR/.env"
fi

# 4. Up
CONFIGURED_HOST="$(grep '^OLYM_HOST=' "$OLYM_DIR/.env" | cut -d= -f2-)"
valid_domain "$CONFIGURED_HOST" || fail "OLYM_HOST in $OLYM_DIR/.env must be a real domain, not a raw IP. Configure its DNS A record and update the file."
log "Confirm DNS A for $CONFIGURED_HOST points to this VPS and that ports 80/443 are publicly reachable."
check_required_ports
check_ufw
log "Starting Olym stack..."
docker compose --project-directory "$OLYM_DIR" up -d

log "Done. Dashboard: https://$(grep '^OLYM_HOST=' "$OLYM_DIR/.env" | cut -d= -f2)"
log "DNS A for $CONFIGURED_HOST must keep pointing to this VPS for HTTPS renewal."
log "Edit $OLYM_DIR/.env (OLYM_HOST, ACME_EMAIL) and re-run to reconfigure."
