#!/usr/bin/env bash
# Olym one-liner installer — draft (F1).
#   curl -fsSL https://get.olym.sh | bash
# Installs Docker if missing, writes /opt/olym/{docker-compose.yml,.env}
# and starts the stack (olym + postgres + redis + traefik).
# No domain is required at install time — the dashboard is reachable
# over plain HTTP on this server's public IP immediately. Configure a
# real domain (and HTTPS) later from Settings inside the dashboard.

set -euo pipefail

OLYM_DIR="${OLYM_DIR:-/opt/olym}"
COMPOSE_URL="${COMPOSE_URL:-https://raw.githubusercontent.com/theinovit/olym/main/docker/docker-compose.prod.yml}"

log() { printf '\033[1;36m[olym]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[olym]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[olym]\033[0m %s\n' "$*" >&2; exit 1; }

port_is_listening() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltnH | awk '{print $4}' | grep -Eq "(^|:|\\])${port}$"
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn | awk 'NR > 2 {print $4}' | grep -Eq "(^|:|\\])${port}$"
  else
    fail "Cannot check ports: install iproute2 (ss) or net-tools (netstat), then re-run."
  fi
}

# Scans upward from $1 until a free TCP port is found (bails after 20 tries).
find_free_port() {
  local candidate="$1" attempts=0
  while port_is_listening "$candidate"; do
    attempts=$((attempts + 1))
    [ "$attempts" -lt 20 ] || fail "Could not find a free port starting near $1 after $attempts attempts."
    candidate=$((candidate + 1))
  done
  printf '%s' "$candidate"
}

# Prefers $1; if it's taken, falls back to scanning upward from $2.
resolve_port() {
  local preferred="$1" fallback_start="$2"
  if ! port_is_listening "$preferred"; then
    printf '%s' "$preferred"
    return
  fi
  find_free_port "$fallback_start"
}

ufw_allows_port() {
  local port="$1"
  ufw status | awk -v wanted="$port" '
    $2 == "ALLOW" {
      rule = $1
      sub(/\/tcp$/, "", rule)
      count = split(rule, ports, ",")
      for (i = 1; i <= count; i++) {
        if (ports[i] == wanted) found = 1
      }
    }
    END { exit(found ? 0 : 1) }
  '
}

check_ufw() {
  local http_port="$1" https_port="$2"
  command -v ufw >/dev/null 2>&1 || return
  ufw status | grep -q '^Status: active' || return
  if ufw status verbose | grep -Eq '^Default: allow \(incoming\)' ||
    { ufw_allows_port "$http_port" && ufw_allows_port "$https_port"; }; then
    return
  fi

  log "UFW is active and does not allow both TCP ports $http_port and $https_port."
  if [ -t 0 ]; then
    local answer
    read -rp "Allow ports $http_port and $https_port now? [y/N] " answer
    case "$answer" in
      y|Y|yes|YES) ufw allow "$http_port,$https_port/tcp" ;;
      *) fail "Firewall unchanged. Run 'ufw allow $http_port,$https_port/tcp' and re-run the installer." ;;
    esac
  else
    fail "UFW blocks web traffic. Run 'ufw allow $http_port,$https_port/tcp' explicitly and re-run the installer."
  fi
}

detect_public_ip() {
  local ip=""
  ip="$(curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null || true)"
  if [ -z "$ip" ]; then
    ip="$(curl -fsSL --max-time 5 https://icanhazip.com 2>/dev/null | tr -d '[:space:]' || true)"
  fi
  if [ -z "$ip" ]; then
    # Last-resort fallback: primary interface address (may be a private/NAT
    # IP behind some providers — DNS verification in Settings will catch a
    # mismatch and tell the user explicitly).
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  [ -n "$ip" ] || fail "Could not detect this server's public IP. Set OLYM_PUBLIC_IP=<ip> and re-run."
  printf '%s' "$ip"
}

[ "$(id -u)" -eq 0 ] || fail "Run as root (or via sudo)."
[ "$(uname -s)" = "Linux" ] || fail "The installer targets Linux servers."

# 1. Docker
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 plugin is required."

# 2. Layout + compose file
mkdir -p "$OLYM_DIR"
log "Downloading compose file to $OLYM_DIR/docker-compose.yml"
curl -fsSL "$COMPOSE_URL" -o "$OLYM_DIR/docker-compose.yml"

# 3. .env (generated once; kept on re-run — ports/IP stay stable across restarts)
if [ ! -f "$OLYM_DIR/.env" ]; then
  log "Generating $OLYM_DIR/.env"
  PUBLIC_IP="${OLYM_PUBLIC_IP:-$(detect_public_ip)}"
  log "Detected public IP: $PUBLIC_IP"

  HTTP_PORT="${OLYM_HTTP_PORT:-$(resolve_port 80 8080)}"
  HTTPS_PORT="${OLYM_HTTPS_PORT:-$(resolve_port 443 8443)}"
  if [ "$HTTP_PORT" != "80" ] || [ "$HTTPS_PORT" != "443" ]; then
    warn "Port 80 and/or 443 already in use on this server — using $HTTP_PORT/$HTTPS_PORT instead."
    warn "Heads up: Let's Encrypt can only validate domains over port 80. Enabling HTTPS on a"
    warn "domain from Settings will not work while Olym runs on a non-standard port — you'll"
    warn "still be able to use everything else over http://$PUBLIC_IP:$HTTP_PORT."
  fi

  cat > "$OLYM_DIR/.env" <<EOF
# Olym configuration — generated by install.sh
OLYM_PUBLIC_IP=$PUBLIC_IP
OLYM_HTTP_PORT=$HTTP_PORT
OLYM_HTTPS_PORT=$HTTPS_PORT
POSTGRES_PASSWORD=$(openssl rand -hex 24)
OLYM_SECRET=$(openssl rand -hex 32)
EOF
  chmod 600 "$OLYM_DIR/.env"
else
  log "Keeping existing $OLYM_DIR/.env"
fi

# 4. Up
HTTP_PORT="$(grep '^OLYM_HTTP_PORT=' "$OLYM_DIR/.env" | cut -d= -f2-)"
HTTPS_PORT="$(grep '^OLYM_HTTPS_PORT=' "$OLYM_DIR/.env" | cut -d= -f2-)"
check_ufw "$HTTP_PORT" "$HTTPS_PORT"
log "Starting Olym stack..."
docker compose --project-directory "$OLYM_DIR" up -d

PUBLIC_IP="$(grep '^OLYM_PUBLIC_IP=' "$OLYM_DIR/.env" | cut -d= -f2-)"
DASHBOARD_URL="http://$PUBLIC_IP"
[ "$HTTP_PORT" = "80" ] || DASHBOARD_URL="$DASHBOARD_URL:$HTTP_PORT"
log "Done. Dashboard: $DASHBOARD_URL"
log "No domain configured yet — the dashboard is reachable over plain HTTP on this IP."
if [ "$HTTP_PORT" = "80" ] && [ "$HTTPS_PORT" = "443" ]; then
  log "Once you've pointed a DNS A record at this server, open Settings inside the dashboard to enable HTTPS on your own domain (applied live, no restart needed)."
else
  log "Running on non-standard ports ($HTTP_PORT/$HTTPS_PORT) — domain/HTTPS setup in Settings won't be able to issue a certificate until Olym has exclusive use of ports 80/443."
fi
